[package]
name = "ootrstats-worker-windows-service-uninstaller"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
windows-service = "0.8"
windows-sys = { version = "0.61.2", features = ["Win32"] }
